### ISSUE TITLE
Target-specific defines for all files

### ISSUE THREAD

**Issue by micprog** [fabianschuiki/bender#40]
To avoid doubly listing files, would it be possible to declare defines for all files depending on the target? As an example, this would allow for tracing-specific signals and blocks to be instantiated without using bender's standard `TARGET_***` defines. Syntax could be similar to below.

```yaml
sources:
  - defines:
      FOO: { target: all(rtl, synth) }
```
